apiVersion: v1
kind: Service
metadata:
  name: python-package-flask-test-service
  labels:
    app: python-package-flask-test
spec:
  selector:
    app: python-package-flask-test
  type: LoadBalancer # for expose as loadbalancer
  # type: NodePort # for expose as nodeport
  ports:
  - port: 5000
    targetPort: http
    # nodePort: 30163 #30000-32767 # uncomment if NodePort used
    protocol: TCP
    name: http

