apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-package-flask-test-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-package-flask-test-service
                port:
                  number: 5000